[package]
name = "libhtmlrewrite"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
autotrait = "0.1.12"

# impl deps
lol_html = { version = "2.3.0" }

[features]
default = ["impl"]
impl = []
