[package]
name = "libcompress"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
bytes = "1.10.1"
brotli = { version = "8.0.0" }
flate2 = { version = "1.1.1" }
autotrait = "0.1.12"
