[package]
name = "libterm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
libclap = { path = "../libclap" }
anstyle-parse = { version = "0.2.6" }
coolor = { version = "1.0.0" }
displaydoc = { version = "0.2.5" }
fs-err = { version = "3.1.0" }
nix = { version = "0.29.0", features = ["process"] }
owo-colors = { version = "4.2.0" }
portable-pty = { version = "0.8.1" }
shell-quote = { version = "0.6.1" }
term_size = { version = "0.3.2" }
termion = { version = "4.0.5" }
tracing = { version = "0.1.41" }
which = { version = "7.0.3" }
autotrait = "0.1.12"
